# Generated by Django 2.2.3 on 2019-07-26 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0003_gameuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameuser',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gameuser',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
