# Generated by Django 2.2.3 on 2019-07-26 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0004_auto_20190726_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameuser',
            name='created_at',
            field=models.DateTimeField(),
        ),
    ]
