# Generated by Django 2.2.3 on 2019-07-26 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0005_auto_20190726_1601'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gameuser',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='gameuser',
            name='updated_at',
        ),
    ]
