# Generated by Django 2.2.3 on 2019-08-02 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0007_post_user_agent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='ip',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
