# Generated by Django 2.2.3 on 2019-08-04 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0008_auto_20190802_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='user_agent',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
